version: '1'

services:

  ############
  #          #
  #  BIND9   #
  #          #
  ############

  bind9:
    container_name: dns-demo
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Rome
    ports:
      - "53:53/udp"
    volumes:
      - ./bind-dns/config:/etc/bind
      - ./bind-dns/cache:/var/cache/bind
      - ./bind-dns/records:/var/lib/bind
  
  #################
  #               #
  #  NGINX HTTP   #
  #               #
  #################
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./fake-pages/src:/var/www/html
      - ./fake-pages/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./fake-pages/src:/var/www/html
      - ./logs:/tmp

  ##################
  #                #
  #  NGINX HTTPS   #
  #                #
  ##################

  nginx:
    image: nginx:latest
    ## Either use host network mode or uncomment the following line
    ports:
      - "443:443"
    volumes:
      - ./https-server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./https-server/certs:/etc/nginx/certs
    network_mode: host
volumes:
  logs: